### ISSUE TITLE
storage parameter on TOAST table gets lost

### ISSUE THREAD

**Issue by pierrestroh** [reorg/pg_repack#10]
hi.

when using pg_repack/pg_reorg (same result) i recognized a missing storage parameter on my TOAST table after reorganization.

the table had set toast.autovacuum_vacuum_scale_factor to 0.1 (via ALTER TABLE mytable SET (toast.autovacuum_vacuum_scale_factor=0.1); )
when running pg_reorg/pg_repack on such table, the storage parameter for the TOAST table was gone.

used command was: pg_repack -n -e -U postgres -d playground -t mytable

server-version: PostgreSQL 9.1.6
pg_repack version 1.1.8

**Comment by dvarrazzo** [comment]
Tentatively work on this issue again. The storage parameters are available on three objects of our interest:

- the tables (in `pg_class.reloptions`)
- the single columns (in `pg_attribute.attoptions`)
- the indexes (in `pg_class.reloptions` too)

there is a remote chance that, because of the way we rebuild indexes, they end up being correct, but if this is the case it has to be tested and added to the test suite anyway.

The tables and the columns require options restoring. This should be done after table creation and before loading data (so e.g. `fillfactor` is honoured etc.)

**Comment by dvarrazzo** [comment]
Note, there is adequate testing that indexes reloptions are handled ok

**Comment by dvarrazzo** [comment]
(I know that's not what the OP requested, but): added test to verify the columns options are respected too. Merging #123 should merge this bug.
