### ISSUE TITLE
Support reordering of columns

### ISSUE THREAD

**Issue by danbst** [reorg/pg_repack#101]
There isn't currently an easy way to reorder columns in Postgres to play "Column tetris", but it would be cool if pg_repack could do this during repack.

**Comment by dvarrazzo** [comment]
We considered that, I would have loved to do it but it cannot be done unfortunately.

**Comment by dvarrazzo** [comment]
@Ten0: postgres catalog has:

- an entry in the table `pg_class` for each table (with `relkind=r`)
  - with a field `relfilenode` pointing at the file on disk containing the data:

```
piro=# select oid, relname, relfilenode from pg_class where relname = 'person';
┌─────────┬─────────┬─────────────┐
│   oid   │ relname │ relfilenode │
├─────────┼─────────┼─────────────┤
│ 9319251 │ person  │     9319251 │
└─────────┴─────────┴─────────────┘
(1 row)

piro=# select oid from pg_database where datname='piro';
┌───────┐
│  oid  │
├───────┤
│ 16385 │
└───────┘
(1 row)

piro=# \q

piro@baloo:~$ sudo ls -l /var/lib/postgresql/12/main/base/16385/9319251
-rw------- 1 postgres postgres 8192 May 13 01:20 /var/lib/postgresql/12/main/base/16385/9319251
```

the way pg_repack (as well as VACUUM FULL work is):

1) create a temporary name with exactly the same schema of the original table (same types, even same dropped columns)
2) fill the new table with the data in the original table
3) update the new table with the data changed since the beginning of point 2
4) swap the relfilenode between the old and the new table
5) drop the new table (which will delete the file pointed by the old relfilenode).

This means that:

- it's not possible to reorder column
- it's not possible to drop delete columns to free up space (but IIRC when copying the data, the data for dropped column is not copied)
- it's not possible to change types if they are not binary compatible (but, in that case, ALTER TABLE would be immediate and wouldn't need to rewrite the table)

try anything of the above and you will most likely get a segfault in the server, because the metadata of the table and the structure of the data in the file won't match.

Is that clear?

**Comment by Ten0** [comment]
Ah I see, that's very clear, thanks a lot!
It looks like this stack overflow answer is mistaken then: https://stackoverflow.com/questions/66685913/how-to-remove-columns-for-real-in-postgresql
I've added a comment there to mention that.

Thanks a lot!

**Comment by Melkij** [comment]
> but IIRC when copying the data, the data for dropped column is not copied

correct. Dropped columns are written with NULL value. This is how PostgreSQL writes such columns itself during an insert or update.

**Comment by asteinlein** [comment]
Are there still no plans of supporting column reordering?

It looks like we would save almost 20% of space for our DB while looking into it after reading a blog post about Postgres' column alignment recently. I had hoped pg_repack would do that as well, but then I came across this issue... When I'm able to reorder a table myself through a manual process, why can't there be a way to do it here too?

**Comment by andreasscherbaum** [comment]
While it's certainly possible to implement this from a technical perspective, I feel like this does not belong into pg_repack, for a variety of reasons:
- It has nothing to do with getting rid of table bloat.
- This is a one-time operation, compared to recurring cleanup tasks pg_repack is doing.
- It adds a lot of complexity: every single place moving data, the trigger functions, every query, needs to be changed to implement this feature. It also requires plenty of test cases to make sure that everything works as expected.
- It might break applications, unintentionally: there are developers who depend on the order of columns in a table.
- It is not clear what is the ideal implementation for reordering columns.

The engineering effort alone makes me reject this request. This is something where a dedicated tool does a better job: just lock the table once, rewrite it into the new structure, and don't bother about all the other tasks. This won't happen every week, schedule a downtime and this saves from all the overhead like streaming the incoming data.

**Comment by Melkij** [comment]
**A lot** more complicated thing: pg_catalog tracks fields by their ordinal numbers. [pg_index](https://www.postgresql.org/docs/current/catalog-pg-index.html).indkey, [pg_attrdef](https://www.postgresql.org/docs/current/catalog-pg-attrdef.html).adnum and so on. Because of this, to simply reorder the fields, we would have to update ALL references in the entire system catalog to the correct new numbers. And, what scares me even more, we would have to track every new postgresql release. Is there a new feature somewhere in pg_catalog that references columns in some way? What if we missed something? The database will be corrupted in a very unpredictable way.

**Comment by andreasscherbaum** [comment]
@Melkij This can be worked around by creating the new table straight with the new structure.

But this still leaves all the other challenges, like every single data move operation must adapt to use the possibly new table structure.

Still a huge effort, not something which can be implemented in passing.

**Comment by asteinlein** [comment]
> While it's certainly possible to implement this from a technical perspective, I feel like this does not belong into pg_repack, for a variety of reasons:
> 
> [...]

Good points, I understand now your concerns and reasons for not wanting this in this tool. Thanks a lot for the clarification. :pray:
