### ISSUE TITLE
latest release?

### ISSUE THREAD

**Issue by MichaelDBA** [reorg/pg_repack#112]
The last release is May 7, 2016.  When will the next one be done with comment#98 included?

**Comment by MasahikoSawada** [comment]
The issue #106 should be included in next release as well.

**Comment by MasahikoSawada** [comment]
Almost 1 year passed since last releasing and some features and bug fixing are incorporated to current HEAD. I think it's good time to release new version of pg_repack. Thought?

PR #97 is still under discussion, I'd like to release new version after merged it. But it would be better to push out it to after next version if it takes a long time.

One more thing, what is the next version number appropriate? v1.3.4? or v1.4.0?

Please give feedback and suggestion.
