### ISSUE TITLE
Migrating PGSQL 9.1.9 to 9.4.6 throws an error....

### ISSUE THREAD

**Issue by scampuza** [reorg/pg_repack#141]
Hi there.

We are trying to perform a PGSQL upgrade from 9.1.9 to 9.4.6 version, the process stops suddenly and then we can see the following in the log file:

pg_restore: creating FUNCTION get_index_keys("oid", "oid")
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 2583; 1255 7687907 FUNCTION get_index_keys("oid", "oid") postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  could not find function "repack_get_index_keys" in file "/usr/local/pgsql-9.4.5/lib/pg_repack.so"
    Command was: CREATE FUNCTION "get_index_keys"("oid", "oid") RETURNS "text"
    LANGUAGE "c" STABLE STRICT
    AS '$libdir/pg_repack', 're..

We have tried to re-compile and reload the pg_repack module several times, but the error keeps appearing.  I have Googled this error and it looks like we are unique with it ( Proud :( ) 

We are downloading, compiling and installing the stable version of the module, pg_repack 1.4.0. 

We are running PGSQL and pg_repack on CentOS release 6.3 (Final).

Thanks in advance with our issue!

**Comment by schmiddy** [comment]
Just to confirm, how are you upgrading -- using `pg_upgrade` or a `pg_dump` plus `pg_restore`?

Looks like we had `repack_get_index_keys` defined back in the 1.1.x releases but not recently, so I'm guessing your source database has an old version of pg_repack installed. You may need exactly the same version installed in your destination database.

Can you either:
 a.) drop the pg_repack extension from your source database, just before migration, in order to migrate without issues
 b.) ensure you have the exact same version of pg_repack installed in your target database

**Comment by scampuza** [comment]
Hi @schmiddy !

Thanks for your quick response.  We are upgrading as follows...

pg_upgrade -b /usr/local/pgsql-9.1.9/bin -B /usr/local/pgsql-9.4.5/bin -d /u01/pgsql/cluster/sys -D /u01/pgsql-9.4.5/cluster/sys --link.

**Comment by scampuza** [comment]
Hi @schmiddy .

Me and my Colleague have double checked and the module pg_repack is not installed in the source DB (9.1.9).  How can we validate any reference or evidence of ever using pg_repack in our DB ?   I ask this because there were other DBA's before me, They could have use that extension and then they dropped it...

Thanks in advance

**Comment by schmiddy** [comment]
You may want to double check **all** databases inside the 9.1.9 cluster, perhaps the pg_repack was installed in one database but not in others (maybe the pg_restore error you posted has some details about which database is at fault). Here's a quick bash command to show all extensions in all databases:

```
for datname in $(psql -t -c 'SELECT datname from pg_database WHERE datallowconn' ) ; do psql -c "\\dx" ; done
```

And you could check for any remnants of the pg_repack extension files installed under your 9.1 server directory:
```
find /usr/local/pgsql-9.1.9/ -type f -name "*repack*"
```

**Comment by scampuza** [comment]
I just run the command 

for datname in $(psql -t -c 'SELECT datname from pg_database WHERE datallowconn' ) ; do psql -c "\\dx" ; done

And found no reference to pg_repack module.  

What else can be invoking the module on 9.1.9 ?

Thanks in advance!

**Comment by schmiddy** [comment]
Hm, well that `get_index_keys` must be defined somewhere if pg_upgrade is trying to restore it into your new database. Another thing you can try is dumping out the entire schema of your old database like this:
```
pg_dumpall -s --file=/tmp/schema.pgdump
```
(be sure you are talking to your 9.1 database here!) and then grep through this schema.pgdump file for lines that talk about `repack` or `get_index_keys`. The `CREATE DATABASE ...` lines above should tell you which database has the extension (and missing functions) defined, and hopefully you can log into that database and drop the extension, or if the extension is not there, drop the `repack` schema and `get_index_keys()` etc.

Way back in the day, I think we used to have pg_repack installed via a .sql installation instead of as a pure extension, especially for versions earlier than 9.1. Even though you're on 9.1 I wonder if you have the remnants of a sufficiently old version that may have been installed with a .sql installer, which would explain why you don't see it with `\dx`.  Either way, you should find it inside the schema-only dump and be able to `DROP` the schema (and any other remnants) that are causing problems.

**Comment by MichaelDBA** [comment]
Closing since bug appears in major upgrades back in the day when pg_repack was distributed via a sql file instead of an extension.
