### ISSUE TITLE
Use pg_repack for upgrading PKs from int4 to int8

### ISSUE THREAD

**Issue by NikolayS** [reorg/pg_repack#197]
There is a common problem: a table was created with int4 PK and, after some time, we have ~1B records in it, approaching int4's limit (2^31), so we need to change it to int8.

It would be great to use pg_repack for such a task. From the first glance, it looks like it can be done just with two hacks – changing plpgsql code of `repack.get_columns_for_create_as` function and patching metadata of the column in `pg_attribute` – see the proof of concept below.

Open questions are:
- [ ] TOASTed tables,
- [ ] indexes metadata (`int4_ops` is shown as AM, but in fact the table/PK accepts big int8 values, see below),
- [ ] sequences should be fine already since they are 8-byte by default. No modifications is needed unless `MINVALUE` was specified explicitly. 

Additional thought: it would be good to have some universal solution here, to support column's type change during repacking. For instance, `timestamp` -> `timestamptz`, `varchar(50)` -> `varchar(100)`, `varchar` -> `text`, etc.

```
test=# create table t1 as select id, 0::int from generate_series(1, 1000000) _(id);
SELECT 1000000
test=# alter table t1 add primary key(id);
ALTER TABLE
test=#
test=# \dt+ t1
                    List of relations
 Schema | Name | Type  |   Owner    | Size  | Description
--------+------+-------+------------+-------+-------------
 public | t1   | table | postgres | 35 MB |
(1 row)

test=# \di+ t1_pkey
                          List of relations
 Schema |  Name   | Type  |   Owner    | Table | Size  | Description
--------+---------+-------+------------+-------+-------+-------------
 public | t1_pkey | index | postgres | t1    | 21 MB |
(1 row)

test=# create extension pg_repack;
CREATE EXTENSION

\ef repack.get_columns_for_create_as

CREATE OR REPLACE FUNCTION repack.get_columns_for_create_as(oid)
 RETURNS text
 LANGUAGE sql
 STABLE STRICT
AS $function$
SELECT array_to_string(repack.array_accum(c), ',') FROM (SELECT
  CASE WHEN attisdropped
    THEN 'NULL::integer AS ' || quote_ident(attname)
    ELSE case when attname = 'id' then quote_ident(attname) || '::int8' else quote_ident(attname) end -- changed this line from "ELSE quote_ident(attname)"
  END AS c
FROM pg_attribute
WHERE attrelid = $1 AND attnum > 0 ORDER BY attnum
) AS COL
$function$
;


test=# \! pg_repack -U postgres -d test -t t1
INFO: repacking table "public.t1"

test=# -- size changed, IDs are int8 already, but metadata is the same, 
test=# -- since pg_repack is swapping files rather than renaming tables
test=# \dt+ t1
                    List of relations
 Schema | Name | Type  |   Owner    | Size  | Description
--------+------+-------+------------+-------+-------------
 public | t1   | table | postgres | 42 MB |
(1 row)

test=# \di+ t1_pkey
                          List of relations
 Schema |  Name   | Type  |   Owner    | Table | Size  | Description
--------+---------+-------+------------+-------+-------+-------------
 public | t1_pkey | index | postgres | t1    | 21 MB |
(1 row)

test=# \d t1
                 Table "public.t1"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 id     | integer  |           | not null |
 int4   | integer |           |          |
Indexes:
    "t1_pkey" PRIMARY KEY, btree (id int4_ops)

test=# -- fix metadata manually
test=# -- **! Hack alert !**
test=# update pg_attribute
       set atttypid = 20 -- 20 is int8, 23 is int4
       where attname = 'id' and attrelid = (
         select oid from pg_class where relname = 't1'
       ) returning *;
-[ RECORD 1 ]-+---------
attrelid      | 71919945
attname       | id
atttypid      | 20
attstattarget | -1
attlen        | 4
attnum        | 1
attndims      | 0
attcacheoff   | -1
atttypmod     | -1
attbyval      | t
attstorage    | p
attalign      | i
attnotnull    | t
atthasdef     | f
attisdropped  | f
attislocal    | t
attinhcount   | 0
attcollation  | 0
attacl        |
attoptions    |
attfdwoptions |
UPDATE 1

test=#

test=# \d t1
                 Table "public.t1"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 id     | bigint  |           | not null |
 int4   | integer |           |          |
Indexes:
    "t1_pkey" PRIMARY KEY, btree (id int4_ops)
test=#                                ^^ 

test=# select (2::int8 ^ 32)::int4;
ERROR:  integer out of range
test=# select (2::int8 ^ 32);
-[ RECORD 1 ]--------
?column? | 4294967296

test=# insert into t1 select (2::int8 ^ 32), 0;
INSERT 0 1
test=#
test=# select * from t1 order by id desc limit 1;
-[ RECORD 1 ]----
id   | 4294967296
int4 | 0
```

**Comment by dvarrazzo** [comment]
Have you seen #162?

**Comment by NikolayS** [comment]
@dvarrazzo, no, thanks. Now I saw it.

So – as I've said, pg_repack doesn't do renaming, but rather it's replacing the file. Ok. But what I propose here is not just `ALTER TABLE ...` for the "shadow" table in `repack` schema. I propose also changing metadata. Why this is a bad idea? Let's discuss it before saying that this is a completely a dead end and switching to pg_squeeze or inventing smth new for such kind of tasks?

I mean -- let's dive into details, why we cannot patch `pg_class`, deal with index metadata, TOAST metadata, etc. Postgres stores metadata in the same structures – tables, with indexes, and SQL can be applied to them easily (of course, if we have permissions for that).

**Comment by Melkij** [comment]
> I propose also changing metadata.
This is strongly required to implement such feature.

We already have dirty hack around postgresql system catalog and we _can_ update another metadata is same manner. C language extension has the necessary rights. Question is about complexity and proper implementation. I think code would be more fragile and it will be more difficult to keep up with new releases of postgresql.

So we need check:
- indexes. With different access methods, some can be added from extensions
- TOAST
- constraints
- sequences are always 8-byte, even you have minvalue or maxvalue (src/backend/commands/sequence.c from postgresql source). But we should carefully recheck GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY syntax, for example
- different data types, and some can be added from extensions

**Comment by joewildish** [comment]
I am also interested in this functionality. I've experimented with exposing the following option:

  `pg_repack --alter="alter table foo alter column n set data type bigint"`

The implementation is done by using the core Postgres machinery to parse the statement and rejecting anything that isn't a `SET DATA TYPE` command. BTW this also means that changing a collation would be supported. Then, a bespoke set of functions, derived from the equivalent ones in the core code, that figures out (a) permission / validity checks and (b) the appropriate `CAST(...)` expressions to use when building the table.

There are a lot of validity checks that we would have to duplicate e.g. reject if the table type is used as a column type for another table, reject if the table is a system catalog, reject if there are unexpected dependencies in `pg_depend`, etc.  If we put this feature in to repack then we'd presumably be commiting to maintaining the set of checks as per core. Is that acceptable?

I am as far as doing some of the validity checks, the `CAST` expression, and the creation of the table. What I am unsure of is the circumstances in which a foreign key would have to be re-validated. The core code seems to always re-validate the referring data when a column has its type changed. However, it seems to me that this can be skipped when there is an implicit `CAST` from the referring data type to the new data type eg. between `BIGINT` and `INTEGER`.  The core code doesn't skip it tho --- so maybe I am missing something? Or, perhaps it is because they have to cater for arbitrary `USING..` expressions? Obviously we need to skip it else the process becomes a blocking operation (so we would reject unless there is an implicit cast, and the `ALTER TABLE` command is written to use such a `CAST`). Any thoughts on this?

**Comment by dvarrazzo** [comment]
This is not possible. I wish it was, badly. But not.

If PostgreSQL gained support to change types (or to drop deleted columns, it's the same issue) in `VACUUM FULL` then we could piggy-back the feature. At the moment PostgreSQL doesn't support it.
