### ISSUE TITLE
Repack into native partitions

### ISSUE THREAD

**Issue by johanndt** [reorg/pg_repack#211]
With the new improvements in native declarative partitioning one of the big gaps so far is how to convert an existing table to a partitioned one.

I'm not sure of the internals of pg_repack but it seems to be that a similar process to repacking can be used except the step which creates a new table should create a partitioned one.

Is this feasible or maybe someone knows of another project which already achieved this?

**Comment by narrowtux** [comment]
I've dabbled a bit in this, and I have identified some blockers:

 * I hacked pg_repacks view so it says `CREATE TABLE ... IF NOT EXISTS` so I can set up the partitions before pg_repack runs
 * pg_repack requires a primary key index, but they are not supported in partitions (only in tables that are partitions of a partitioned table, i.e. leaf nodes; but that doesn't help). The primary key is used for the log table that pg_repack creates to keep track of changes while the table is copied. In our case, we have a UUID primary key, which is perfect since it doesn't actually need to be enforced to be unique, the chances for a duplicate are super low. So it could be solved with a flag that you enter the primary key into.

**Comment by simi** [comment]
:thinking: I'm pretty interested in this and I would consider this a "killer feature". But per my understanding, maintainers are not interesting in maintaining such a code since it seems out of scope of this project.

some references

https://github.com/reorg/pg_repack/pull/162
https://github.com/reorg/pg_repack/issues/306

**Comment by andreasscherbaum** [comment]
> how to convert an existing table to a partitioned one

I consider this a job for a tool which manages partitions, like [pg_partman](https://github.com/pgpartman/pg_partman). Dealing with table bloat in such a partition is a side effect, which might not even the case all the time.

**Comment by Melkij** [comment]
now we just replace relfilenode with a new one. Migration to the partition tree... Relation swap won't be so easy. We will have to (correctly!) rewrite all links in the system catalog. I'm even more frightened here by tracking the appearance of new links in new versions of postgresql.

**Comment by andreasscherbaum** [comment]
Implementing repacking into native partitions will next ask for also create partitions, maybe create missing partitions on the fly, handle default partitions, split up the data using all kind of query logic - and suddenly pg_repack becomes a full fledged migration tool. And what about inherited tables? The question then becomes: where to draw the line.

Implement one task and implement it well. Other tools can handle partition migration and might call pg_repack under the hood, if necessary.

**Comment by za-arthur** [comment]
Closing the issue due to discussion above.
