### ISSUE TITLE
Linking issues on Windows (MSVC 2017)

### ISSUE THREAD

**Issue by arteika** [reorg/pg_repack#242]
Hi Developers,

Thanks a lot for a great extension. We are shipping our software with postgres on windows (quite a few old versions of it as well as the newer ones), and this extension would help a lot to keep the databases in tidy shape.

Since our primarily deployment environment is windows, I tried to compile and link it under windows. I download the 2017 version of MSVC and with a few adjustments:

- remove _USE_32BIT_TIME_T
- update include paths
- update library paths

managed to compile (and mostly link) the package. However, I get this linking error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol set_pglocale_pgservice	bin.2010	\pg_repack\msvc\pgut.obj	1	
Error	LNK2001	unresolved external symbol pgwin32_select	bin.2010	 \pg_repack\msvc\pg_repack.obj	1	
Error	LNK2001	unresolved external symbol __imp__dclass	bin.2010	 \pg_repack\msvc\libpgport.lib(snprintf.obj)	1	
```

How can I get this linked properly?

**Comment by arteika** [comment]
It looks to me, that the pgwin32_select and set_pglocale_pgservice symbols can be found in postgres.lib

**Comment by arteika** [comment]
It seems to me that MSVC does not allow partial initialization of structs (as well as named initialization). Shouldn't the code

```
worker_conns workers  = {
	.num_workers     = 0,
	.conns           = NULL
};
```

be replaced with

```worker_conns workers  = { 0, 0, NULL };```

or am I wrong here? It looks that this issue was already mentioned in numerous lists.. I wonder how the developers managed to get this compiled under msvc2010?

**Comment by arteika** [comment]
Compiling lib.2010 subproject fails as it cannot find `pgut-be.c` file. Removing this from the solution compiles the project

**Comment by dvarrazzo** [comment]
@arteika,

window is not supported by pg_repack. Supporting windows for me would mean at least:

- fix the source to ensure it compiles
- set up the build toolchain
- create an installation package
- set up the build toolchain on a CI to create and test these packages automatically.

If your company would like to sponsor the work on these tasks please get in touch. Otherwise the correct way to contribute to the project is to send a MR implementing the above points, and taking on the responsibility of maintaining those packages for the time being.

Personally, I am finishing a few projects for customers, and will start spending more time on free-software project in the coming month: pg_repack can be one to focus on, if there is interest. Please look at [my sponsorship profile](https://github.com/sponsors/dvarrazzo) for further information.

Thank you.

**Comment by dvarrazzo** [comment]
Closing as no interest in supporting Windows adequately has been expressed.
