### ISSUE TITLE
pg_repack not stopping

### ISSUE THREAD

**Issue by e-jjj** [reorg/pg_repack#287]
Hi There,

I have run pg_repack from an ubuntu machine, it ran for hours (more than 9hours) against a large database. The client connection was finally stopped and I then ran the DROP EXTENSION pg_repack CASCADE; in the database, which ran for more than 5 hours without stopping or dropping the extension.

The following query against the log table shows that the repacking is very slow and not able to catch up with live data as far as I understand.
1.
select now(), min(id),max(id),max(id)-min(id) as left from repack.log_32368;
now                            min  max       left
"2021-09-01 09:25:44.042099+00"	1	8473128	8473127

select now(), min(id),max(id),max(id)-min(id) as left from repack.log_32368;
now                            min   max.     left
"2021-09-01 09:28:40.556512+00"	1	8477424	8477423

Can you please assist? How can i stop the repacking as the log table keeps increasing and I dont see much value at this stage.

Thanks in advance

**Comment by schmiddy** [comment]
If you only kicked off a single run against the database, hopefully pg_repack has only left its table and trigger on the one table it was in the middle of processing. To get rid of the remnants of pg_repack left on that table, I think it'd be like this based on your `repack.log_32368` table name:

 * `DROP TABLE IF EXISTS repack.log_32368 CASCADE;`
 * `DROP TYPE IF EXISTS repack.pk_32368;`
 * `DROP TRIGGER IF EXISTS repack_trigger ON your_table CASCADE;`
 * `DROP TABLE IF EXISTS repack.table_32368;`

That said, the `DROP EXTENSION pg_repack CASCADE;` should have done basically this - since you said this tried to run for 5 hours, maybe that command was waiting on a lock. The commands above should get rid of the pg_repack pieces for just that one table, and maybe let you see a little more clearly what is blocked (these should all be fast, unless there is a locking issue).

**Comment by ncleaton** [comment]
If the problem is with obtaining the `ACCESS EXCLUSIVE` lock on your_table to drop the trigger, you could try `ALTER TABLE your_table DISABLE TRIGGER repack_trigger;` which does not need quite such a strong lock and will prevent the log table from growing any more for now.

**Comment by MichaelDBA** [comment]
Too long without a response from issue creator to try the recommended solutions.  Closing accordingly.
