### ISSUE TITLE
pg_repack failed on a Large Table

### ISSUE THREAD

**Issue by moindba** [reorg/pg_repack#312]
Hello Team,

I would like to know the scenario, that if we initiated pg_repack on a large table and after sometime pg_repack got failed with some errors. Then will it impact my table  and indexes ? 

How safe my table data and indexes if pg_repack failed ? will it be a lost of data and corruption of indexes if pg_repack failed.

What will be resolution / steps i need to follow that if pg_repack failed then it shouldn't impact my table data and indexes.

Regards,
Moin

**Comment by xzilla** [comment]
This question is a bit too open ended to give specific answers, because the specifics would depend on the nature of the failure, however in the vast majority of failure cases, either pg_repack will rollback any changes it has made automagically, or you may need to drop the pg_repack schema/objects that were created during your repack run. In either case, your original tables/indexes should remain intact and corruption free.

**Comment by MichaelDBA** [comment]
Question answered correctly by @xzilla
